### ISSUE TITLE
Treesitter Vim Broken: Failed to Execute the Following Command...

### ISSUE THREAD

**Issue by UnrealApex** [vigoux/tree-sitter-viml#126]
When running `:TSUpdate` I get the following error and treesitter-vim fails to load:
![image](https://user-images.githubusercontent.com/79121360/189784660-00749d38-31f2-4aab-b888-9977c2c1384f.png)

What could be causing the problem here?

FYI I am on Windows.

**Comment by vigoux** [comment]
Hi, I think you should report this issue in `nvim-treesitter` instead of here as it concerns installation of the parser.

To be clearer, the parser installation is ensured on CI for all supported platforms in nvim-treesitter, so the issue must come from here.

I am going to transfer the issue there to avoid duplication.
