### ISSUE TITLE
autocommand error on `term://*`

### ISSUE THREAD

**Issue by doubleloop** [vigoux/tree-sitter-viml#35]
```vim
au BufWinEnter,WinEnter,FocusGained term://* startinsert
```
```
autocmd_statement [239, 2] - [240, 0]
  au_event_list [239, 5] - [239, 37]
    au_event [239, 5] - [239, 16]
    au_event [239, 17] - [239, 25]
    au_event [239, 26] - [239, 37]
  pattern [239, 38] - [239, 42]
  ERROR [239, 42] - [239, 46]
  command: command [239, 47] - [240, 0]
    command_name [239, 47] - [239, 58]
```

**Comment by vigoux** [comment]
There is actually two issue here: 
- autocmds patterns are too restricted
- `startinsert` is not supported.

**Comment by doubleloop** [comment]
I was reading the fix for `startinsert` support (to be able to add other missing commands) and I just wander, is it required to add separate statement for each vim command? Maybe the better solution would be to add generic `command_statement`, the rule for it would be a big `choice` listing all possible commands.

**Comment by vigoux** [comment]
The problem is that many (if not all) bultin commands have specific arguments, that can be parsed.
Some of them (like `startinsert`) don't take any arguments, but I think that, for consistency, we should keep the different statements separated.

Now that I think of it though, we can _hide_ all of these statements from the end user, but I think it refrains the possibility to build customized queries.
